---
- name: Install Updates
  hosts: host
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
    ansible_python_interpreter: /usr/bin/python3

  tasks: 

    - name: install aptitude 
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes  

    - name: install required packages
      apt:
        pkg:
          - openjdk-8-jdk
          - apt-transport-https
          - software-properties-common
          - ca-certificates
          - wget
          - python2.7
          - python3          
          - python3-pip
        state: latest
        update_cache: true
      
    - name: open ports
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: open ports
      community.general.ufw:
        rule: allow
        port: '9200'
        # proto: tcp

    - name: open ports
      community.general.ufw:
        rule: allow
        port: '5601'
        # proto: tcp

    - name: print echo
      shell: echo "Updates have been applied" > update.txt

    - name: Display update.txt contents
      command: cat update.txt
      register: update_output

    - name: Print to console
      debug:
        msg: "{{ update_output.stdout_lines }}"

    # - name: Print to console
    #   ansible.builtin.debug: 
    #     msg: "Updates Completed!"
